[package]
name = "bevy_editor"
version = "0.1.0"
edition = "2021"

[[bin]]
path = "src/main.rs"
name = "BevyEditor"

[dependencies]
bevy = { version = "0.15", features = ["serialize"] }
bevy_egui = "0.31"
egui_dock = { version = "0.14", features = ["serde"] }
transform-gizmo-egui = "0.4"
bevy-inspector-egui = "0.28"

serde = "1.0"
serde_json = "1.0"
directories = "5.0"

[workspace]
resolver = "2"

# Enable a small amount of optimization in debug mode
[profile.dev]
opt-level = 1

# Enable high optimizations for dependencies (incl. Bevy), but not for our code:
[profile.dev.package."*"]
opt-level = 3