[package]
name = "bevy_creator"
version = "0.1.0"
edition = "2021"

[[bin]]
path = "src/main.rs"
name = "BevyCreator"

[dependencies]
bevy = { version = "0.15.0", features = ["serialize"] }
serde = "1.0.217"
serde_json = "1.0"
directories = "5.0.1"
bevy_egui = "0.31"
egui_dock = { version = "0.14.0", features = ["serde"] }
bevy-inspector-egui = "0.28.0"
transform-gizmo-bevy = { git = "https://github.com/ethereumdegen/transform-gizmo.git" }

# image = { version = "0.24", default-features = false }
# once_cell = "1.16"
# pretty-type-name = "1.0"
# smallvec = "1.10"
# egui-gizmo = "0.12"ะะต

# ron = "0.8.1"
# bevy_mod_picking = { version = "0.17.0", default-features = false, features = [
#     "backend_raycast",
#     "backend_bevy_ui",
#     "backend_sprite",
#     "backend_egui",
#     "debug",
#     "selection",
#     "highlight",
# ] }

[workspace]
resolver = "2"

# Enable a small amount of optimization in debug mode
[profile.dev]
opt-level = 1

# Enable high optimizations for dependencies (incl. Bevy), but not for our code:
[profile.dev.package."*"]
opt-level = 3
